### ISSUE TITLE
Table data download

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#1]
Download CSV feature does not work

**Comment by byndcivilization** [comment]
This will come once table directives are done.

**Comment by byndcivilization** [comment]
@KseniyaKuprina can you implement https://github.com/asafdav/ng-csv and add to download links?

**Comment by davidmihalyi** [comment]
Not all downloads work, ie on company page: http://dev.resourceprojects.org/country/AD    

payment download is called production.csv on project page. can you rename that?

**Comment by davidmihalyi** [comment]
@byndcivilization

**Comment by byndcivilization** [comment]
Code is merged but not pushed to server yet.

**Comment by davidmihalyi** [comment]
cool, i was not sure.

**Comment by byndcivilization** [comment]
working now
