### ISSUE TITLE
project ID

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#14]
the project ID convention we put down our vote on last year.
2digit countrycode / 4 characters from project name - 6 random characters.

if project name has one word - pick first 4 characters of the project name (smal cap)
if project name has 2 or more word - pick  2 char from first word and 2 from second word 
Examples:
gh/juﬁ-3f3eu3   - Jubilee Field (Ghana)
za/agne-11geq3 -  Agnes (South Africa)
pe/alri-yqcee o- Alpamarca Rio Pallanga (Peru)

http://alpha.resourceprojects.org/project/PE/alri-yqceeo.html
http://alpha.resourceprojects.org/project/ZA/agne-11geq3.html

**Comment by byndcivilization** [comment]
Is there a reason for the slash instead of a -?

**Comment by byndcivilization** [comment]
My hunch is that the back slash is a linked data holdover, can we modify this as

- 2digit countrycode - 4 characters from project name - 6 random characters.

so 

- http://alpha.resourceprojects.org/project/PE-alri-yqceeo.html

**Comment by davidmihalyi** [comment]
No idea why it was backslash instead of ?.
@anderspeders  any idea?
I`d be fine with changing that.
d

**Comment by byndcivilization** [comment]
@mattfullerton you are assigning this on the etl side right? I need to do some researche on the mongoose regex validator but its a fairly straightforward pattern.

**Comment by mattfullerton** [comment]
Do we generate the random pattern in Google Sheets or at import?

**Comment by davidmihalyi** [comment]
google sheets allows to look up existing IDs right now, which is super helpful.
my hunch is that new IDs are better generated at import, but not sure.

**Comment by byndcivilization** [comment]
Either way there will need to be logic to check if it exists and generate if not to account for non Google sheet data
