### ISSUE TITLE
Typehead dependancies not right

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#18]
The current includes/scripts calls bootstrap-typeahead.js. This doesnt seem to be in the bower file. Ive removed it but we're still getting a typehead error.

**Comment by mattfullerton** [comment]
It is in there as typeahead not bootstrap-typeahead - I remember doing some work to fix that. The problem I'm seeing is that the js file is getting passed through a template.

**Comment by byndcivilization** [comment]
Are bottstrap-typehead and typehead distinct? I think this code ported from the old alpha site and not really sure what its for. Isnt typhead for autocompletion?

**Comment by mattfullerton** [comment]
I think typeahead is the successor. I assumed it was for search etc. autocompleton, but only tried to fix the dependency to get a clean run of the site.

**Comment by byndcivilization** [comment]
I'll depricate it for now until we start hitting the search functionality
