### ISSUE TITLE
Deal with company stakes in contracts and concessions

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#29]
We want to give the ability to store and display percentage of company stake in a given concession, project or contract. Agnostic on whether this happens via a referenced model or on a subdocument.

**Comment by byndcivilization** [comment]
This is  #project+company+share in the spreadsheet

**Comment by byndcivilization** [comment]
this will need to be handled either as a fact array or through the link model

**Comment by byndcivilization** [comment]
Because of deduplication process we may need to think about storing stake as a link and is operator as a fact array

**Comment by byndcivilization** [comment]
@mattfullerton 
- adding [entity]_operated_by as fact array on project, site and concession level
- handling stakes as links

**Comment by byndcivilization** [comment]
scratch that im dealing with company share as a fact array on project, concession, and site models.

- proj_company_share
- site_company_share
- concession_company_share

**Comment by anderspeders** [comment]
For reference: RC.org has [participation share] captured in metadata at value span [0;1]: 
https://github.com/NRGI/resourcecontracts.org/wiki/Contract-Metadata-API

See example: 
http://www.resourcecontracts.org/contract/ocds-591adf-CD8092339396RC

Would encourage that we consider interoperability here - just not sure which of the three it would map towards.

**Comment by mattfullerton** [comment]
This is done for concessions, we have no data in GS for projects - although I can copy it across as the concession is always linked directly to a project. Should I do that?

**Comment by davidmihalyi** [comment]
The spreadsheet is misleading in conflating concesion and project ownership, but those should really be copied over to project ownerships. Yes, let's use that until this is cleared up (concesion ownership may come from external Api in next iteration)

**Comment by mattfullerton** [comment]
ok - will do

**Comment by mattfullerton** [comment]
Just want to note that the title talks about contracts but these are a foreign import from RC. See also #62 and #69.
