### ISSUE TITLE
Remove project column from production stats on project page

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/rp-org-frontend#37]
If these are the prod stats for a proj, why display the project? It doesn't seem to be working anyway.

**Comment by byndcivilization** [comment]
This needs to be fleshed out but it should be populated with any projects and sites linked to the production. This sort of predates the production/transfer as direct ref so it probably makes more sense to call title this column sites in this case. We could also lose it, though its meant to show cases where a payment or production record is linked to both a site and a project.

**Comment by davidmihalyi** [comment]
I agree we can lose it as for soft launch: all our production data is only linked to a project (and not to sites)
