### ISSUE TITLE
0.5 validation issues - to be fixed before loading

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/rp-org-frontend#42]
- Kosmos: Invalid commodities in projects sheet
- Ghana: Spurious (0.6?) columns in projects sheet
- Mali: Invalid status info in project sheet (construction/development`. Please select exploration, development, production, on hold, inactive or unknown..)
- Norway Tullow 2013: Spurios column "Payment note" between payments and receipts, AND value "unknown" used for accounting basis when only cash or accrual are allowed
- Tullow 2014: value "unknown" used for accounting basis when only cash or accrual are allowed
- PH-EITI: Spurious (0.6?) columns in projects sheet
- EITI: Please remove line break from project name
"Mayaro-
Guayaguayare Horizons (Petrotrin B)"
and update all references

- Mexico: Spurious (0.6?) columns in projects sheet
- Peru: ONLY ONE Spurious (0.6?) column in projects sheet
- Norwegian Companies: Invalid commodities in projects sheet
- Statoil: Company names are entered in capitals but referenced using mixed case
- World Bank Mines: Spurious (0.6?) columns in projects sheet

N.B. There are so many sheets with the "spurious columns", and some of them contain data, we probably should rather make a 0.5a template standard whereby all 0.5 sheets gain these columns.

**Comment by davidmihalyi** [comment]
is it a problem to have unused column in the spreadsheet?

**Comment by davidmihalyi** [comment]
are they not captured via their column name?

**Comment by mattfullerton** [comment]
Currently, no. Unused columns are not a problem, just different column layouts in different sheets. I would say one version of the template should be the same for all sheets. But for future-proofing identifying the columns by column name is definitely a sensible idea. I'll open an issue.

**Comment by davidmihalyi** [comment]
All fixed except one problem....
= (construction/development`. Please select exploration, development, production, on hold, inactive or unknown..). Our current validation sheet uses construction/development. I coudl rename that across all sheet, but unclear if this is necessary.

**Comment by mattfullerton** [comment]
The only current problem is that "Mandatory Payment Disclosure" should be changed to one of:
Generic Mandatory payment 
UK Mandatory payment 
Norway Mandatory payment disclosure

The sheets Tullow 2014, Tullow 2013, Norwegian Companies and Statoil are affected.

The problem with caps vs. proper case in references kept coming up. The import no longer cares for sources or companies, but note that the name of the entity will be that in either the source list or company list respectively and not that of the reference.

**Comment by davidmihalyi** [comment]
Sure, fixed disclosures above in GS based on code list here https://github.com/NRGI/rp-org-frontend/blob/master/server/models/SourceTypes.js

**Comment by davidmihalyi** [comment]
Will need fixing also in 0.6 template

**Comment by davidmihalyi** [comment]
What happened on construction/development status @mattfullerton ?

**Comment by mattfullerton** [comment]
The workaround as proposed by @byndcivilization was used: word after "/" is taken.

**Comment by davidmihalyi** [comment]
Great, was just checking. Thanks
