### ISSUE TITLE
How does the site establish commodity to [X] linkages?

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/rp-org-frontend#43]
Do we need to create links here? There are no dummy links in Links.js. Not seeing any project counts on commodities page.

**Comment by mattfullerton** [comment]
I am only storing them as facts in projects under project_commodity.

**Comment by byndcivilization** [comment]
They should be stored as facts wherever relevant. I'm pulling them through links on the controllers. For example a countries commodity list will be populated by all the unique commodities attached to projects, sites, concessions and contracts.

**Comment by byndcivilization** [comment]
- contract linkage is offsite in the RC.org datamodel
- concessions, sites, projects, transfers, and production all have ability to store commodity values as fact arrays

**Comment by byndcivilization** [comment]
Not sure how this affects ETL atm since we're only really dealing with projects.

**Comment by mattfullerton** [comment]
OK, then I think this doesn't need any explicit linking on my part and should then be working with the revised controllers, right?
