### ISSUE TITLE
ETL: some fact dates not coming through

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#49]
so far project status only shows a few time stamps. The ones that do come through are kind of random:

timestamp: "2015-01-01T05:00:00.000Z" - jan 1 2015
timestamp: "1970-01-01T00:00:02.014Z" - dec 31 1969

**Comment by mattfullerton** [comment]
This will be a problem with date parsing, which is a bit tricky as sometimes the sheets have a nice date taken from a real spreadsheet date type and other times it's text.

**Comment by davidmihalyi** [comment]
Maybe hide dates for now completely since super scarcely populated or only take year 4 digit (ie 19Xx or 20xx )?

**Comment by byndcivilization** [comment]
there isnt a 4 year for most. We need to enforce timestamping. A workaround could be just to time stamp load time for existing sheets and work on template formatting for future sheets.

**Comment by mattfullerton** [comment]
Done. 2014 now yields this: "timestamp" : ISODate("2014-01-01T00:00:00Z")
