### ISSUE TITLE
ETL Duplicate sources

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#52]
We're getting duplicate sources coming in i think.

I havent done a ton of investigating but at least
"Exportações e Receitas de Petróleo 2014" is entered twice with the same metadata

**Comment by davidmihalyi** [comment]
There is two entries in GS with similar name, can that be the cause?
Exportações e Receitas de Petróleo 2014
Exportações e Receitas de Petróleo 2009
or it might be the random Spanish characters?

**Comment by byndcivilization** [comment]
no it was two called Exportações e Receitas de Petróleo 2014 and pointing to the same source pdf

**Comment by byndcivilization** [comment]
Either way i think its fixed
