### ISSUE TITLE
ETL multi level array propegation

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#53]
I'm getting funny stuff int the country fact arrays. it looks like the first entry is pushed correctly and each further country ref is pushed as an array on key '0'.
```
concession_country: 
   [ { timestamp: Thu Mar 24 2016 13:39:16 GMT-0400 (EDT),
       _id: 56f426daa23ea321a959631c,
       source: 56f426d9a23ea321a959623f,
       country: [Object] },
     { '0': [Object],
       timestamp: Fri Mar 25 2016 16:05:48 GMT-0400 (EDT),
       country: null },
     { '0': [Object],
       timestamp: Fri Mar 25 2016 16:05:48 GMT-0400 (EDT),
       country: null } ]
```

**Comment by byndcivilization** [comment]
Just want to flag that this is still happening but only on concessions

**Comment by mattfullerton** [comment]
Fixed. I was sending data formatted for a create to an $addToSet which already knows its working with arrays and wants array elements not fresh arrays.
