### ISSUE TITLE
ETL Off site IDs

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#55]
are we storing things like the open corporates id as an id or a url?

**Comment by mattfullerton** [comment]
Although we want the id, the url is in the sheet.I should detect url and extract ID actually, right?

**Comment by davidmihalyi** [comment]
Yes, that would probably be best way around!
Thanks

**Comment by byndcivilization** [comment]
so for now we will only really handle RC-ids on contracts even though the model supports it
