### ISSUE TITLE
ETL field flag

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#56]
This wasnt set to default to false on the model and wasnt explicitly being handled on etl. I'm setting default to false, meaning that all sites that come in will default to sites and not fields. @mattfullerton want to make sure this wont break anything

**Comment by mattfullerton** [comment]
This won't break anything, but it needs to be included in ETL with the 0.6 update. Have noted it in the issue there.

**Comment by davidmihalyi** [comment]
probably a short hand more likely right default would be to say field for where project is oil and gas and site for project is mining. but can be handled in next iteration.

**Comment by mattfullerton** [comment]
In the 0.5 ETL the default was "true" and if commodity type was "mining" it was set to false. So I'm disputing a little the point that this wasn't being handled but more to the point want to check again which way round it should be.

I think it's all irrelevant now due to 0.6 upgrade.

**Comment by davidmihalyi** [comment]
oil: field = true
mining: field = false (site=true)
live site is good on this

0.6 wont need default on dummy
