### ISSUE TITLE
Opencorporates link broken

### ISSUE THREAD

**Issue by anderspeders** [NRGI/rp-org-frontend#58]
An error in auto-linking to OC

Example: 
http://dev.resourceprojects.org/company/56f6c0dcb5eafb01007ed33b

Links to this URL: 
https://opencorporates.com/companies/https://opencorporates.com/companies/je/EXTUID_24670

**Comment by mattfullerton** [comment]
Duplicate of #55

**Comment by byndcivilization** [comment]
As a quick fix im changing the template. Let me know when ETL is pulling OC id.

**Comment by mattfullerton** [comment]
I've fixed ETL and changed the template back
