### ISSUE TITLE
Top menu

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#60]
@byndcivilization  Can we have top menu as the following? -

Projects Payments Other Data(dropdown) About(dropdown) Admin(dropdown)
Sites and fields would be moved to other data.

**Comment by davidmihalyi** [comment]
you shared comment about displaying  placeholder text on payment page (describing what this page will do) for alpha launch not being great,but think it is important to signal what is coming. happy to chat on that.

**Comment by byndcivilization** [comment]
info about coming payment page will be in about page -> roadmap

**Comment by davidmihalyi** [comment]
what about moving sites and fields to other data? is that OK?

I will need to talk to Jim again on having no payment page, he seems pretty strong on wanting one.

**Comment by davidmihalyi** [comment]
will draft a roadmap in the meantime...

**Comment by byndcivilization** [comment]
This is closed. If @jimc33 wants to push it he can open a new ticket and push it, but I dont see it happening in time.
