### ISSUE TITLE
Company duplicates appear 

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#61]
@byndcivilization  notes: "I think the duplicate companies is on the get controller. They link to the same company entity. The server side logic is that it should only push to the array if it doesn't exist so there's a bug in there

See here:
http://dev.resourceprojects.org/project/gh-jubi-zpqzhc
This is a page we want to show during webinar, so would be great to fix if not too much work.

**Comment by byndcivilization** [comment]
seems to be working now.
