### ISSUE TITLE
default for site and field boolean

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#65]
default type=field if oil_gas and type=site if mining.
if n/a or both (i don`t think that exists) - then type=field.

**Comment by mattfullerton** [comment]
This is a site entity property (site in the sense of DB model, not site vs. field). The project commodity type is, for example with Angola, set once for the overall project and not for the site. When there is no commodity type listed for the site, should we inherit from the project? Or do you want to amend the sheets to make it clear?

**Comment by davidmihalyi** [comment]
yes, please inherit it from project!

if there is any confusion or n/a, we should default to field.

**Comment by davidmihalyi** [comment]
we need to rework this in 0.6 template anyways...

**Comment by mattfullerton** [comment]
There is a slight inconsistency here, because technically speaking, projects and sites can have multiple commodities because this is an array of facts. So fact 1 might say mining and fact 2 oil/gas. It's probably irrelevant for 99% of cases

**Comment by mattfullerton** [comment]
OK, done
