### ISSUE TITLE
location does not always store

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/rp-org-frontend#67]
It stores in Peru but not Mexico
it does not store on Jubilee project either.
both are currently in site details:
http://dev.resourceprojects.org/sites/map

**Comment by davidmihalyi** [comment]
@mattfullerton please have a look...

**Comment by mattfullerton** [comment]
Please take a look at locations on the newest dev deploy and have a good think about where the Jubilee data is coming from. This should be somewhat or fully fixed now providing data in the sheets is sensible.

**Comment by davidmihalyi** [comment]
It is fixed!
