### ISSUE TITLE
ETL commodities not in some sheets.

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rp-org-frontend#84]
there are some sheets where only the commodity type is entered, not the commodity. We need commodity entered in all of these.

this is at least the case in:

- https://docs.google.com/spreadsheets/d/1KDhQpIXLcy4uI8FJ17W9r7NPQIiQBdzjSzSCX7K9L7w/edit#gid=141760938
- https://docs.google.com/spreadsheets/d/1nArJqi0RnyZ_WsKO9zxCSZGkG5ltonPVnoSvIZVWpww/pub#
- https://docs.google.com/spreadsheets/d/17FDwVbDCReeWxufE2Gab1yw1PqJpQIt6pASM92d7sl4/pub#

**Comment by davidmihalyi** [comment]
Done
